'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { Check, Clock3, Flame, LockKeyhole, RotateCcw, Settings2, Sparkles, Star, Trophy, Volume2, VolumeX, WandSparkles } from 'lucide-react'

type TableState = { solved: number; stars: number; unlocked: boolean; claimed: boolean; seen: number[]; failed: number[]; cycle: number; times: number[]; rewardVariant: number }
type Progress = { stars: number; streak: number; tables: Record<number, TableState>; answers: number[]; random: boolean; sound: boolean }
const labels = ['La nube','El bosque','La charca','La cueva','El castillo','La galaxia','La isla','La luna','El laboratorio','El arcoíris']
const funnyNames = ['Nube coronada','Rana astronauta','Fresa bailarina','Dragón estornudón','Pingüino héroe','Plátano guitarrista','Pulpo patinador','Luna bigotuda','Robot abrazable','Unicornio bailarín']
const blank = (): TableState => ({ solved: 0, stars: 0, unlocked: false, claimed: false, seen: [], failed: [], cycle: 0, times: [], rewardVariant: 1 })
const rewardSrc = (table: number, variant: number) => `/rewards/table-${table}${variant === 1 ? '' : `-${variant}`}.png`
const makeTables = () => Object.fromEntries(Array.from({ length: 10 }, (_, i) => [i + 1, { ...blank(), unlocked: true }])) as Record<number, TableState>
const initial: Progress = { stars: 0, streak: 0, tables: makeTables(), answers: [], random: false, sound: true }
function celebrate() { try { const C = window.AudioContext || (window as any).webkitAudioContext; const c = new C(); [523, 659, 784, 1047].forEach((f, i) => { const o = c.createOscillator(), g = c.createGain(), t = c.currentTime + i * .07; o.type = 'triangle'; o.frequency.value = f; g.gain.setValueAtTime(.001, t); g.gain.exponentialRampToValueAtTime(.14, t + .02); g.gain.exponentialRampToValueAtTime(.001, t + .2); o.connect(g).connect(c.destination); o.start(t); o.stop(t + .22) }) } catch {} }

export default function Home() {
 const [progress, setProgress] = useState<Progress>(initial), [table, setTable] = useState(1), [factor, setFactor] = useState(1), [answer, setAnswer] = useState(''), [result, setResult] = useState<'correct'|'wrong'|null>(null), [hint, setHint] = useState(false), [showSettings, setShowSettings] = useState(false), [started, setStarted] = useState(Date.now()), [notice, setNotice] = useState(''), [rewardModal, setRewardModal] = useState(false)
 const answerInputRef = useRef<HTMLInputElement>(null)
 const focusAnswer = () => { requestAnimationFrame(() => answerInputRef.current?.focus()) }
 useEffect(() => { const saved = localStorage.getItem('tabliaventura-progress'); if (saved) try { const p = JSON.parse(saved); const tables = { ...makeTables(), ...p.tables }; Object.keys(tables).forEach(k => { tables[+k] = { ...blank(), ...tables[+k], unlocked: true, seen: tables[+k].seen || [], failed: tables[+k].failed || [], times: tables[+k].times || [], rewardVariant: Math.min(5, Math.max(1, tables[+k].rewardVariant || 1)) } }); setProgress({ ...initial, ...p, tables }) } catch {} }, [])
 useEffect(() => { localStorage.setItem('tabliaventura-progress', JSON.stringify(progress)) }, [progress])
 const data = progress.tables[table] ?? blank(), target = table * factor, unlocked = useMemo(() => Object.values(progress.tables).filter(x => x.unlocked).length, [progress.tables])
 const pick = (p: Progress, t = table, seenOverride?: number[]) => { const d = p.tables[t] ?? blank(), seen = seenOverride ?? d.seen, pool = Array.from({ length: 10 }, (_, i) => i + 1).filter(n => !seen.includes(n)); if (!pool.length) return p.random ? Math.floor(Math.random() * 10) + 1 : 1; return p.random ? pool[Math.floor(Math.random() * pool.length)] : pool[0] }
 const chooseTable = (n: number) => { setTable(n); setFactor(pick(progress, n)); setAnswer(''); setResult(null); setHint(false); setStarted(Date.now()); setNotice(''); focusAnswer() }
 const check = () => { if (!answer || result === 'correct') return; const ok = Number(answer) === target; const elapsed = Math.round((Date.now() - started) / 100) / 10; setResult(ok ? 'correct' : 'wrong'); if (!ok) { setProgress(p => ({ ...p, tables: { ...p.tables, [table]: { ...p.tables[table], failed: [...p.tables[table].failed, factor] } } })); return }
  if (progress.sound) celebrate(); setProgress(p => { const old = p.tables[table] ?? blank(), seen = old.seen.includes(factor) ? old.seen : [...old.seen, factor], solved = seen.length, complete = solved === 10, nextCycle = complete ? old.cycle + 1 : old.cycle; return { ...p, stars: p.stars + 10, streak: p.streak + 1, tables: { ...p.tables, [table]: { ...old, seen: complete ? [] : seen, solved: complete ? 10 : solved, cycle: nextCycle, claimed: false, stars: old.stars + 10, times: [...old.times, elapsed].slice(-30) }, ...(complete && table < 10 ? { [table + 1]: { ...blank(), ...(p.tables[table + 1] ?? {}), unlocked: true } } : {}) }, answers: [target, ...p.answers].slice(0, 12) } }); const completedRound = seenLength(progress, table, factor) === 10; if (completedRound) { setNotice(`¡Emma, has completado la tabla del ${table}! Tu premio está listo.`) } setTimeout(() => { setFactor(p => pick(p, table, completedRound ? [] : (p.tables[table]?.seen ?? []))); setAnswer(''); setResult(null); setHint(false); setStarted(Date.now()); focusAnswer() }, 700)
 }
 const seenLength = (p: Progress, t: number, f: number) => p.tables[t].seen.includes(f) ? p.tables[t].seen.length : p.tables[t].seen.length + 1
 const claim = () => { if (data.solved !== 10 || data.claimed) return; const variant = Math.floor(Math.random() * 5) + 1; setProgress(p => ({ ...p, tables: { ...p.tables, [table]: { ...p.tables[table], claimed: true, solved: 0, seen: [], rewardVariant: variant } } })); setNotice(`¡Premio conseguido, Emma! Has desbloqueado una imagen sorpresa.`); setRewardModal(true) }
 const reset = () => { if (confirm('¿Borramos toda tu aventura, Emma?')) { setProgress(initial); setTable(1); setFactor(1); setAnswer(''); setResult(null) } }
 const avg = data.times.length ? (data.times.reduce((a, b) => a + b, 0) / data.times.length).toFixed(1) : '—'
 return <main className="min-h-screen bg-background text-foreground"><div className="mx-auto flex min-h-screen max-w-[1480px] flex-col px-5 py-5 sm:px-8 lg:px-12">
  <header className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-primary text-primary-foreground shadow-[0_5px_0_var(--navy-dark)]"><WandSparkles size={23}/></div><div><p className="font-mono text-[10px] uppercase tracking-[.22em] text-muted-foreground">aventura de Emma</p><p className="font-heading text-xl font-black">Emma la Calculadora</p></div></div><div className="flex items-center gap-2 rounded-full border border-border bg-card px-3 py-2"><Star className="text-sun" fill="currentColor" size={18}/><b>{progress.stars}</b><Flame className="ml-2 text-coral" fill="currentColor" size={18}/><b>{progress.streak}</b><button aria-label="Configuración" className="ml-2 rounded-full p-1 hover:bg-secondary" onClick={() => setShowSettings(!showSettings)}><Settings2 size={17}/></button></div></header>
  {showSettings && <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-border bg-card p-4"><div className="flex flex-wrap gap-2"><button onClick={() => setProgress(p => ({ ...p, random: false }))} className={`rounded-full px-3 py-2 text-sm font-bold ${!progress.random ? 'bg-teal text-primary' : 'bg-secondary'}`}>Orden seguido</button><button onClick={() => setProgress(p => ({ ...p, random: true }))} className={`rounded-full px-3 py-2 text-sm font-bold ${progress.random ? 'bg-teal text-primary' : 'bg-secondary'}`}>Orden aleatorio</button><button aria-label="Sonido" onClick={() => setProgress(p => ({ ...p, sound: !p.sound }))} className="rounded-full bg-secondary p-2">{progress.sound ? <Volume2 size={18}/> : <VolumeX size={18}/>}</button></div><button onClick={reset} className="text-sm font-bold text-coral">Reiniciar progreso</button></div>}
  <div className="grid flex-1 gap-8 pb-8 pt-10 lg:grid-cols-[1fr_360px] lg:gap-14"><section><div className="mb-8"><div className="mb-4 inline-flex items-center gap-2 rounded-full bg-teal/15 px-3 py-1.5 font-mono text-[10px] font-bold uppercase tracking-widest text-teal-dark"><Sparkles size={13}/> misión de Emma</div><h1 className="max-w-2xl font-heading text-5xl font-black leading-[.98] tracking-[-.055em] sm:text-6xl">Emma rescata las estrellas de <span className="text-coral">{labels[table - 1]}</span></h1><p className="mt-4 text-muted-foreground">Tabla del {table}: {data.solved}/10 retos nuevos resueltos.</p></div>
  <div className="rounded-[2rem] border border-border bg-card p-6 shadow-[0_10px_0_var(--border)] sm:p-8"><div className="flex items-center justify-between"><p className="font-mono text-xs uppercase tracking-widest text-muted-foreground">reto {Math.min(data.solved + 1, 10)} / 10</p><span className="rounded-full bg-sun/30 px-3 py-2 font-mono text-xs font-bold">+ 10 estrellas</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-teal transition-all" style={{ width: `${data.solved * 10}%` }}/></div><div className="mt-7 rounded-2xl bg-primary px-5 py-10 text-center text-primary-foreground"><p className="font-mono text-xs uppercase tracking-widest opacity-60">¿cuánto es?</p><p className="mt-3 font-heading text-6xl font-black">{table} × {factor} <span className="text-sun">= ?</span></p></div><div className="mt-5 flex flex-col gap-2 sm:flex-row"><input ref={answerInputRef} aria-label="Respuesta de Emma" inputMode="numeric" value={answer} onChange={e => { setAnswer(e.target.value.replace(/[^0-9]/g, '')); setResult(null) }} onKeyDown={e => { if (e.key === 'Enter' && !e.nativeEvent.isComposing && e.keyCode !== 229) check() }} placeholder="Respuesta de Emma" className="min-h-14 flex-1 rounded-xl border-2 border-border bg-background px-4 font-heading text-xl font-bold outline-none focus:border-teal"/><button onClick={check} className="min-h-14 rounded-xl bg-coral px-6 font-heading font-black text-primary shadow-[0_4px_0_var(--coral-dark)]">Comprobar</button></div>{result && <div aria-live="polite" className={`mt-4 rounded-xl p-3 text-center font-bold ${result === 'correct' ? 'bg-teal/20 text-teal-dark' : 'bg-coral/15 text-coral-dark'}`}>{result === 'correct' ? `¡Bravo, Emma! ${target} es correcto. Siguiente reto...` : 'Casi. Esta operación volverá a salir para practicarla.'}</div>}<div className="mt-3 flex flex-wrap gap-2"><button onClick={() => setHint(!hint)} className="rounded-xl bg-secondary px-3 py-2 text-sm font-bold">{hint ? `Pista: ${table} sumado ${factor} veces` : 'Dame una pista'}</button><span className="flex items-center gap-1 rounded-xl bg-secondary px-3 py-2 text-sm font-bold text-muted-foreground"><Clock3 size={15}/> Media: {avg}s</span></div></div>
  {notice && <div role="status" className="mt-4 rounded-2xl border-2 border-sun bg-sun/25 p-4 text-center font-heading font-black">{notice}</div>}
  <div className="mt-6 rounded-2xl bg-sun/20 p-4"><p className="font-heading font-bold">Premios de Emma</p><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-5">{Array.from({ length: 10 }, (_, i) => { const d = progress.tables[i + 1]; return <button key={i} onClick={() => chooseTable(i + 1)} className="relative overflow-hidden rounded-xl border border-border bg-card p-2 text-left" title={funnyNames[i]}><div className="relative aspect-square overflow-hidden rounded-lg bg-secondary">{d?.claimed ? <img src={rewardSrc(i + 1, d.rewardVariant)} alt={funnyNames[i]}/> : <div className="grid h-full place-items-center text-muted-foreground"><LockKeyhole size={18}/></div>}</div><span className="mt-1 block truncate text-[10px] font-bold">Tabla {i + 1}</span>{d?.cycle > 1 && <span className="block text-[9px] text-coral">Premio {d.cycle}</span>}</button> })}</div></div></section>
  <aside><div className="rounded-[1.75rem] border border-border bg-card p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-heading text-lg font-black">Mapa de Emma</h2><p className="text-xs text-muted-foreground">{unlocked} mundos disponibles</p></div><Trophy className="text-sun" size={28}/></div><div className="flex flex-col gap-2">{Array.from({ length: 10 }, (_, i) => { const n = i + 1, d = progress.tables[n], current = n === table; return <button key={n} onClick={() => chooseTable(n)} className={`flex items-center gap-3 rounded-xl border p-3 text-left ${current ? 'border-teal bg-teal/10' : 'border-transparent bg-secondary/60'} ${!d.unlocked ? 'opacity-50' : ''}`}><div className={`grid size-9 place-items-center rounded-lg font-heading font-black ${d.solved === 10 ? 'bg-sun' : current ? 'bg-teal' : 'bg-muted'}`}>{d.unlocked ? (d.solved === 10 ? <Check size={17}/> : n) : <LockKeyhole size={15}/>}</div><div className="flex-1"><p className="font-heading text-sm font-black">Tabla del {n}</p><p className="text-[10px] text-muted-foreground">{labels[i]} · {d.solved}/10 · media {d.times?.length ? (d.times.reduce((a, b) => a + b, 0) / d.times.length).toFixed(1) : '—'}s</p></div>{d.cycle > 0 && <Star className="text-sun" fill="currentColor" size={15}/>}</button> })}</div></div>{data.solved === 10 && <div className="mt-4 rounded-2xl bg-primary p-5 text-primary-foreground"><p className="font-mono text-xs uppercase tracking-widest text-sun">premio para Emma</p><p className="mt-2 font-heading font-black">{funnyNames[table - 1]}</p>{data.claimed ? <img className="mx-auto mt-3 size-28 rounded-xl" src={rewardSrc(table, data.rewardVariant)} alt={funnyNames[table - 1]}/> : <button onClick={claim} className="mt-3 w-full rounded-xl bg-sun px-3 py-3 font-bold text-primary">Comprar / reclamar premio</button>}</div>}</aside></div></div>{rewardModal && <div role="dialog" aria-modal="true" aria-labelledby="reward-title" className="fixed inset-0 z-50 grid place-items-center bg-primary/60 p-5"><div className="w-full max-w-sm rounded-[2rem] border-2 border-sun bg-card p-6 text-center shadow-[0_10px_0_var(--navy-dark)]"><Sparkles className="mx-auto text-sun" size={34}/><h2 id="reward-title" className="mt-2 font-heading text-2xl font-black">¡Premio para Emma!</h2><p className="mt-1 text-sm text-muted-foreground">Has completado 10 retos de la tabla del {table}.</p><img className="mx-auto mt-4 size-44 rounded-2xl object-cover" src={rewardSrc(table, data.rewardVariant)} alt={funnyNames[table - 1]}/><p className="mt-3 font-heading text-lg font-black">{funnyNames[table - 1]}</p><button autoFocus onClick={() => setRewardModal(false)} className="mt-5 w-full rounded-xl bg-coral px-4 py-3 font-heading font-black text-primary shadow-[0_4px_0_var(--coral-dark)]">¡Qué divertido!</button></div></div>}</main>
}
